name: 'Setup Nix'
description: 'Installs Nix and configures binary caches'
runs:
  using: 'composite'
  steps:
    - name: Install Nix
      # "DeterminateSystems/nix-installer-action" does not run on x86_64-darwin: https://github.com/DeterminateSystems/nix-src/issues/224
      uses: cachix/install-nix-action@2126ae7fc54c9df00dd18f7f18754393182c73cd # v31.9.1
      with:
        extra_nix_config: |
          sandbox = true
          accept-flake-config = true
