name: 'Setup Nix'
description: 'Installs Nix and configures binary caches'
runs:
  using: 'composite'
  steps:
    - name: Install Nix
      # "DeterminateSystems/nix-installer-action" does not run on x86_64-darwin: https://github.com/DeterminateSystems/nix-src/issues/224
      uses: NixOS/nix-installer-action@main # There are no tagged releases
      with:
        extra-conf: |
          sandbox = true
          accept-flake-config = true
