name: 'Setup Nix'
description: 'Installs Nix and configures binary caches'
runs:
  using: 'composite'
  steps:
    - name: Install Nix
      uses: NixOS/nix-installer-action@62c1943b776c509394b550f3f983adc14e9212d6 # v1.0.0
      with:
        extra-conf: |
          sandbox = true
          accept-flake-config = true
